version: '3.7'

services:
  db:
    image: postgres
    container_name: flatype_db
    networks:
      - flatype
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ../flatype/db_dev:${DB_DATA_PATH}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: ${DB_DATA_PATH}

  web:
    build:
      context: ..
      dockerfile: ./deployment/dockerfiles/Dockerfile
    image: flatype
    container_name: flatype_web
    networks:
      - flatype
    depends_on:
      - db
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    volumes:
      - ../flatype/deployment:/opt/app/deployment
      - ../flatype/templates:/opt/app/templates
      - ../flatype/public:/opt/app/public
      - ../flatype/src:/opt/app/src
    command: bash -c "./deployment/scripts/gunicorn.sh"
    environment:
      WEB_PORT: ${WEB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      LEVEL: ${LEVEL}
      HOST: ${HOST}

networks:
  flatype:
    name: flatype
    driver: bridge
  nginx:
    external:
      name: nginx
